import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const templates = [
  // ============================================
  // RUGBY UNION
  // ============================================
  {
    sport: 'rugby_union',
    name: 'Rugby Union Full Field',
    description: 'World Rugby regulation field (15-a-side)',
    minLength: 94,
    maxLength: 100,
    minWidth: 68,
    maxWidth: 70,
    defaultLength: 100,
    defaultWidth: 70,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Field boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'halfway_line',
          type: 'line',
          description: 'Halfway line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'try_line_top',
          type: 'line',
          description: 'Try line / Goal line (top)',
          start: { x: 0, y: 0 },
          end: { x: 'field_width', y: 0 },
        },
        {
          id: 'try_line_bottom',
          type: 'line',
          description: 'Try line / Goal line (bottom)',
          start: { x: 0, y: 'field_length' },
          end: { x: 'field_width', y: 'field_length' },
        },
        {
          id: '22m_line_top',
          type: 'line',
          description: '22-meter line (top)',
          start: { x: 0, y: 22 },
          end: { x: 'field_width', y: 22 },
        },
        {
          id: '22m_line_bottom',
          type: 'line',
          description: '22-meter line (bottom)',
          start: { x: 0, y: 'field_length - 22' },
          end: { x: 'field_width', y: 'field_length - 22' },
        },
        {
          id: '10m_line_top',
          type: 'line',
          description: '10-meter line from halfway (top)',
          start: { x: 0, y: '(field_length / 2) - 10' },
          end: { x: 'field_width', y: '(field_length / 2) - 10' },
        },
        {
          id: '10m_line_bottom',
          type: 'line',
          description: '10-meter line from halfway (bottom)',
          start: { x: 0, y: '(field_length / 2) + 10' },
          end: { x: 'field_width', y: '(field_length / 2) + 10' },
        },
        {
          id: '5m_dash_top',
          type: 'line',
          description: '5-meter line (top, dashed)',
          start: { x: 0, y: 5 },
          end: { x: 'field_width', y: 5 },
        },
        {
          id: '5m_dash_bottom',
          type: 'line',
          description: '5-meter line (bottom, dashed)',
          start: { x: 0, y: 'field_length - 5' },
          end: { x: 'field_width', y: 'field_length - 5' },
        },
        {
          id: 'center_mark',
          type: 'point',
          description: 'Center spot',
          position: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 0.3,
        },
      ],
      fixedElements: ['22m_line_top', '22m_line_bottom', '10m_line_top', '10m_line_bottom', '5m_dash_top', '5m_dash_bottom'],
      specifications: {
        tryLineToDeadBall: 10,
        twentyTwoMeterLine: 22,
        tenMeterLine: 10,
        fiveMeterLine: 5,
        goalPostWidth: 5.6,
      },
    },
  },

  // ============================================
  // RUGBY LEAGUE
  // ============================================
  {
    sport: 'rugby_league',
    name: 'Rugby League Full Field',
    description: 'NRL/International regulation field (13-a-side)',
    minLength: 100,
    maxLength: 122,
    minWidth: 68,
    maxWidth: 68,
    defaultLength: 100,
    defaultWidth: 68,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Field boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'halfway_line',
          type: 'line',
          description: 'Halfway line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'try_line_top',
          type: 'line',
          description: 'Try line (top)',
          start: { x: 0, y: 0 },
          end: { x: 'field_width', y: 0 },
        },
        {
          id: 'try_line_bottom',
          type: 'line',
          description: 'Try line (bottom)',
          start: { x: 0, y: 'field_length' },
          end: { x: 'field_width', y: 'field_length' },
        },
        {
          id: '40m_line_top',
          type: 'line',
          description: '40-meter line (top)',
          start: { x: 0, y: 40 },
          end: { x: 'field_width', y: 40 },
        },
        {
          id: '40m_line_bottom',
          type: 'line',
          description: '40-meter line (bottom)',
          start: { x: 0, y: 'field_length - 40' },
          end: { x: 'field_width', y: 'field_length - 40' },
        },
        {
          id: '20m_line_top',
          type: 'line',
          description: '20-meter line (top)',
          start: { x: 0, y: 20 },
          end: { x: 'field_width', y: 20 },
        },
        {
          id: '20m_line_bottom',
          type: 'line',
          description: '20-meter line (bottom)',
          start: { x: 0, y: 'field_length - 20' },
          end: { x: 'field_width', y: 'field_length - 20' },
        },
        {
          id: '10m_line_top',
          type: 'line',
          description: '10-meter line (top)',
          start: { x: 0, y: 10 },
          end: { x: 'field_width', y: 10 },
        },
        {
          id: '10m_line_bottom',
          type: 'line',
          description: '10-meter line (bottom)',
          start: { x: 0, y: 'field_length - 10' },
          end: { x: 'field_width', y: 'field_length - 10' },
        },
        {
          id: 'center_mark',
          type: 'point',
          description: 'Center spot',
          position: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 0.3,
        },
      ],
      fixedElements: ['40m_line_top', '40m_line_bottom', '20m_line_top', '20m_line_bottom', '10m_line_top', '10m_line_bottom'],
      specifications: {
        fortyMeterLine: 40,
        twentyMeterLine: 20,
        tenMeterLine: 10,
        inGoalDepth: 8,
      },
    },
  },

  // ============================================
  // AFL (AUSTRALIAN FOOTBALL)
  // ============================================
  {
    sport: 'afl',
    name: 'AFL Full Field',
    description: 'Australian Football League regulation oval',
    minLength: 135,
    maxLength: 185,
    minWidth: 110,
    maxWidth: 155,
    defaultLength: 165,
    defaultWidth: 135,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Oval boundary (approximation)',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_circle',
          type: 'circle',
          description: 'Center circle',
          center: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 3,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'center_square',
          type: 'rectangle',
          description: 'Center square',
          position: { x: '(field_width - 50) / 2', y: '(field_length - 50) / 2' },
          size: { width: 50, height: 50 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'goal_square_top',
          type: 'rectangle',
          description: 'Goal square (top)',
          position: { x: '(field_width - 6.4) / 2', y: 0 },
          size: { width: 6.4, height: 9 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'goal_square_bottom',
          type: 'rectangle',
          description: 'Goal square (bottom)',
          position: { x: '(field_width - 6.4) / 2', y: 'field_length - 9' },
          size: { width: 6.4, height: 9 },
          size_unit: 'meters_fixed',
        },
        {
          id: '50m_arc_top',
          type: 'arc',
          description: '50-meter arc (top)',
          center: { x: 'field_width / 2', y: 0 },
          radius: 50,
          startAngle: 0,
          endAngle: 180,
        },
        {
          id: '50m_arc_bottom',
          type: 'arc',
          description: '50-meter arc (bottom)',
          center: { x: 'field_width / 2', y: 'field_length' },
          radius: 50,
          startAngle: 180,
          endAngle: 360,
        },
      ],
      fixedElements: ['center_circle', 'center_square', 'goal_square_top', 'goal_square_bottom', '50m_arc_top', '50m_arc_bottom'],
      specifications: {
        centerCircleRadius: 3,
        centerSquareSize: 50,
        goalSquareWidth: 6.4,
        goalSquareDepth: 9,
        fiftyMeterArc: 50,
        goalPostSpacing: 6.4,
        behindPostSpacing: 6.4,
      },
    },
  },

  // ============================================
  // FIELD HOCKEY
  // ============================================
  {
    sport: 'hockey',
    name: 'Field Hockey Full Pitch',
    description: 'FIH regulation hockey pitch',
    minLength: 91.4,
    maxLength: 91.4,
    minWidth: 55,
    maxWidth: 55,
    defaultLength: 91.4,
    defaultWidth: 55,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Field boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_line',
          type: 'line',
          description: 'Center line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: '23m_line_top',
          type: 'line',
          description: '23-meter line (top)',
          start: { x: 0, y: 22.9 },
          end: { x: 'field_width', y: 22.9 },
        },
        {
          id: '23m_line_bottom',
          type: 'line',
          description: '23-meter line (bottom)',
          start: { x: 0, y: 'field_length - 22.9' },
          end: { x: 'field_width', y: 'field_length - 22.9' },
        },
        {
          id: 'circle_top',
          type: 'arc',
          description: 'Shooting circle (top)',
          center: { x: 'field_width / 2', y: 0 },
          radius: 14.63,
          startAngle: 0,
          endAngle: 180,
        },
        {
          id: 'circle_bottom',
          type: 'arc',
          description: 'Shooting circle (bottom)',
          center: { x: 'field_width / 2', y: 'field_length' },
          radius: 14.63,
          startAngle: 180,
          endAngle: 360,
        },
        {
          id: 'penalty_spot_top',
          type: 'point',
          description: 'Penalty spot (top)',
          position: { x: 'field_width / 2', y: 6.4 },
          radius: 0.15,
        },
        {
          id: 'penalty_spot_bottom',
          type: 'point',
          description: 'Penalty spot (bottom)',
          position: { x: 'field_width / 2', y: 'field_length - 6.4' },
          radius: 0.15,
        },
        {
          id: 'center_mark',
          type: 'point',
          description: 'Center spot',
          position: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 0.15,
        },
      ],
      fixedElements: ['23m_line_top', '23m_line_bottom', 'circle_top', 'circle_bottom', 'penalty_spot_top', 'penalty_spot_bottom'],
      specifications: {
        circleRadius: 14.63,
        penaltySpotDistance: 6.4,
        twentyThreeMeterLine: 22.9,
        goalWidth: 3.66,
      },
    },
  },

  // ============================================
  // CRICKET
  // ============================================
  {
    sport: 'cricket',
    name: 'Cricket Pitch',
    description: 'ICC regulation cricket pitch/wicket area',
    minLength: 20.12,
    maxLength: 20.12,
    minWidth: 3.05,
    maxWidth: 3.05,
    defaultLength: 20.12,
    defaultWidth: 3.05,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Pitch boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'crease_popping_top',
          type: 'line',
          description: 'Popping crease (top)',
          start: { x: 0, y: 1.22 },
          end: { x: 'field_width', y: 1.22 },
        },
        {
          id: 'crease_popping_bottom',
          type: 'line',
          description: 'Popping crease (bottom)',
          start: { x: 0, y: 'field_length - 1.22' },
          end: { x: 'field_width', y: 'field_length - 1.22' },
        },
        {
          id: 'crease_bowling_top',
          type: 'line',
          description: 'Bowling crease (top)',
          start: { x: 0, y: 0 },
          end: { x: 'field_width', y: 0 },
        },
        {
          id: 'crease_bowling_bottom',
          type: 'line',
          description: 'Bowling crease (bottom)',
          start: { x: 0, y: 'field_length' },
          end: { x: 'field_width', y: 'field_length' },
        },
        {
          id: 'crease_return_top_left',
          type: 'line',
          description: 'Return crease (top-left)',
          start: { x: '(field_width / 2) - 1.32', y: 0 },
          end: { x: '(field_width / 2) - 1.32', y: 2.64 },
        },
        {
          id: 'crease_return_top_right',
          type: 'line',
          description: 'Return crease (top-right)',
          start: { x: '(field_width / 2) + 1.32', y: 0 },
          end: { x: '(field_width / 2) + 1.32', y: 2.64 },
        },
        {
          id: 'crease_return_bottom_left',
          type: 'line',
          description: 'Return crease (bottom-left)',
          start: { x: '(field_width / 2) - 1.32', y: 'field_length' },
          end: { x: '(field_width / 2) - 1.32', y: 'field_length - 2.64' },
        },
        {
          id: 'crease_return_bottom_right',
          type: 'line',
          description: 'Return crease (bottom-right)',
          start: { x: '(field_width / 2) + 1.32', y: 'field_length' },
          end: { x: '(field_width / 2) + 1.32', y: 'field_length - 2.64' },
        },
      ],
      fixedElements: ['crease_popping_top', 'crease_popping_bottom', 'crease_return_top_left', 'crease_return_top_right', 'crease_return_bottom_left', 'crease_return_bottom_right'],
      specifications: {
        pitchLength: 20.12,
        poppingCreaseDistance: 1.22,
        returnCreaseWidth: 2.64,
        stumpWidth: 0.2286,
      },
    },
  },

  // ============================================
  // TENNIS
  // ============================================
  {
    sport: 'tennis',
    name: 'Tennis Court (Singles & Doubles)',
    description: 'ITF regulation tennis court',
    minLength: 23.77,
    maxLength: 23.77,
    minWidth: 10.97,
    maxWidth: 10.97,
    defaultLength: 23.77,
    defaultWidth: 10.97,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Doubles court boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'singles_sideline_left',
          type: 'line',
          description: 'Singles sideline (left)',
          start: { x: 1.37, y: 0 },
          end: { x: 1.37, y: 'field_length' },
        },
        {
          id: 'singles_sideline_right',
          type: 'line',
          description: 'Singles sideline (right)',
          start: { x: 'field_width - 1.37', y: 0 },
          end: { x: 'field_width - 1.37', y: 'field_length' },
        },
        {
          id: 'net_line',
          type: 'line',
          description: 'Net line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'service_line_top',
          type: 'line',
          description: 'Service line (top)',
          start: { x: 1.37, y: 5.485 },
          end: { x: 'field_width - 1.37', y: 5.485 },
        },
        {
          id: 'service_line_bottom',
          type: 'line',
          description: 'Service line (bottom)',
          start: { x: 1.37, y: 'field_length - 5.485' },
          end: { x: 'field_width - 1.37', y: 'field_length - 5.485' },
        },
        {
          id: 'center_service_line_top',
          type: 'line',
          description: 'Center service line (top)',
          start: { x: 'field_width / 2', y: 0 },
          end: { x: 'field_width / 2', y: 5.485 },
        },
        {
          id: 'center_service_line_bottom',
          type: 'line',
          description: 'Center service line (bottom)',
          start: { x: 'field_width / 2', y: 'field_length' },
          end: { x: 'field_width / 2', y: 'field_length - 5.485' },
        },
        {
          id: 'center_mark_top',
          type: 'line',
          description: 'Center mark (top baseline)',
          start: { x: 'field_width / 2', y: 0 },
          end: { x: 'field_width / 2', y: 0.1 },
        },
        {
          id: 'center_mark_bottom',
          type: 'line',
          description: 'Center mark (bottom baseline)',
          start: { x: 'field_width / 2', y: 'field_length' },
          end: { x: 'field_width / 2', y: 'field_length - 0.1' },
        },
      ],
      fixedElements: ['singles_sideline_left', 'singles_sideline_right', 'service_line_top', 'service_line_bottom', 'center_service_line_top', 'center_service_line_bottom'],
      specifications: {
        doublesWidth: 10.97,
        singlesWidth: 8.23,
        serviceLineDistance: 6.4,
        netHeight: 0.914,
        alleyWidth: 1.37,
      },
    },
  },

  // ============================================
  // BASKETBALL
  // ============================================
  {
    sport: 'basketball',
    name: 'Basketball Court (FIBA)',
    description: 'FIBA regulation basketball court',
    minLength: 28,
    maxLength: 28,
    minWidth: 15,
    maxWidth: 15,
    defaultLength: 28,
    defaultWidth: 15,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Court boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_line',
          type: 'line',
          description: 'Center line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'center_circle',
          type: 'circle',
          description: 'Center circle',
          center: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 1.8,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'three_point_arc_top',
          type: 'arc',
          description: 'Three-point arc (top)',
          center: { x: 'field_width / 2', y: 1.575 },
          radius: 6.75,
          startAngle: 0,
          endAngle: 180,
        },
        {
          id: 'three_point_arc_bottom',
          type: 'arc',
          description: 'Three-point arc (bottom)',
          center: { x: 'field_width / 2', y: 'field_length - 1.575' },
          radius: 6.75,
          startAngle: 180,
          endAngle: 360,
        },
        {
          id: 'key_top',
          type: 'rectangle',
          description: 'Key/Paint (top)',
          position: { x: '(field_width - 4.9) / 2', y: 0 },
          size: { width: 4.9, height: 5.8 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'key_bottom',
          type: 'rectangle',
          description: 'Key/Paint (bottom)',
          position: { x: '(field_width - 4.9) / 2', y: 'field_length - 5.8' },
          size: { width: 4.9, height: 5.8 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'free_throw_circle_top',
          type: 'circle',
          description: 'Free throw circle (top)',
          center: { x: 'field_width / 2', y: 5.8 },
          radius: 1.8,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'free_throw_circle_bottom',
          type: 'circle',
          description: 'Free throw circle (bottom)',
          center: { x: 'field_width / 2', y: 'field_length - 5.8' },
          radius: 1.8,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'restricted_area_top',
          type: 'arc',
          description: 'Restricted area arc (top)',
          center: { x: 'field_width / 2', y: 1.575 },
          radius: 1.25,
          startAngle: 0,
          endAngle: 180,
        },
        {
          id: 'restricted_area_bottom',
          type: 'arc',
          description: 'Restricted area arc (bottom)',
          center: { x: 'field_width / 2', y: 'field_length - 1.575' },
          radius: 1.25,
          startAngle: 180,
          endAngle: 360,
        },
      ],
      fixedElements: ['center_circle', 'three_point_arc_top', 'three_point_arc_bottom', 'key_top', 'key_bottom', 'free_throw_circle_top', 'free_throw_circle_bottom', 'restricted_area_top', 'restricted_area_bottom'],
      specifications: {
        threePointRadius: 6.75,
        keyWidth: 4.9,
        keyDepth: 5.8,
        freeThrowRadius: 1.8,
        restrictedAreaRadius: 1.25,
        rimHeight: 3.05,
      },
    },
  },

  // ============================================
  // NETBALL
  // ============================================
  {
    sport: 'netball',
    name: 'Netball Court',
    description: 'INF regulation netball court',
    minLength: 30.5,
    maxLength: 30.5,
    minWidth: 15.25,
    maxWidth: 15.25,
    defaultLength: 30.5,
    defaultWidth: 15.25,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Court boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_line',
          type: 'line',
          description: 'Center line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'center_circle',
          type: 'circle',
          description: 'Center circle',
          center: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 0.45,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'goal_third_line_top',
          type: 'line',
          description: 'Goal third line (top)',
          start: { x: 0, y: 10.167 },
          end: { x: 'field_width', y: 10.167 },
        },
        {
          id: 'goal_third_line_bottom',
          type: 'line',
          description: 'Goal third line (bottom)',
          start: { x: 0, y: 'field_length - 10.167' },
          end: { x: 'field_width', y: 'field_length - 10.167' },
        },
        {
          id: 'goal_circle_top',
          type: 'arc',
          description: 'Goal circle (top)',
          center: { x: 'field_width / 2', y: 0 },
          radius: 4.9,
          startAngle: 0,
          endAngle: 180,
        },
        {
          id: 'goal_circle_bottom',
          type: 'arc',
          description: 'Goal circle (bottom)',
          center: { x: 'field_width / 2', y: 'field_length' },
          radius: 4.9,
          startAngle: 180,
          endAngle: 360,
        },
      ],
      fixedElements: ['center_circle', 'goal_third_line_top', 'goal_third_line_bottom', 'goal_circle_top', 'goal_circle_bottom'],
      specifications: {
        thirdLength: 10.167,
        goalCircleRadius: 4.9,
        centerCircleRadius: 0.45,
        goalPostHeight: 3.05,
      },
    },
  },

  // ============================================
  // AMERICAN FOOTBALL
  // ============================================
  {
    sport: 'american_football',
    name: 'American Football Field',
    description: 'NFL/NCAA regulation football field',
    minLength: 109.7,
    maxLength: 109.7,
    minWidth: 48.8,
    maxWidth: 48.8,
    defaultLength: 109.7,
    defaultWidth: 48.8,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Field boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'end_zone_top',
          type: 'rectangle',
          description: 'End zone (top)',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 9.144 },
        },
        {
          id: 'end_zone_bottom',
          type: 'rectangle',
          description: 'End zone (bottom)',
          position: { x: 0, y: 'field_length - 9.144' },
          size: { width: 'field_width', height: 9.144 },
        },
        {
          id: 'goal_line_top',
          type: 'line',
          description: 'Goal line (top)',
          start: { x: 0, y: 9.144 },
          end: { x: 'field_width', y: 9.144 },
        },
        {
          id: 'goal_line_bottom',
          type: 'line',
          description: 'Goal line (bottom)',
          start: { x: 0, y: 'field_length - 9.144' },
          end: { x: 'field_width', y: 'field_length - 9.144' },
        },
        // 10-yard lines (every 9.144m from goal line)
        {
          id: '10_yard_line_1',
          type: 'line',
          description: '10 yard line',
          start: { x: 0, y: 18.288 },
          end: { x: 'field_width', y: 18.288 },
        },
        {
          id: '20_yard_line_1',
          type: 'line',
          description: '20 yard line',
          start: { x: 0, y: 27.432 },
          end: { x: 'field_width', y: 27.432 },
        },
        {
          id: '30_yard_line_1',
          type: 'line',
          description: '30 yard line',
          start: { x: 0, y: 36.576 },
          end: { x: 'field_width', y: 36.576 },
        },
        {
          id: '40_yard_line_1',
          type: 'line',
          description: '40 yard line',
          start: { x: 0, y: 45.72 },
          end: { x: 'field_width', y: 45.72 },
        },
        {
          id: '50_yard_line',
          type: 'line',
          description: '50 yard line (midfield)',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: '40_yard_line_2',
          type: 'line',
          description: '40 yard line',
          start: { x: 0, y: 'field_length - 45.72' },
          end: { x: 'field_width', y: 'field_length - 45.72' },
        },
        {
          id: '30_yard_line_2',
          type: 'line',
          description: '30 yard line',
          start: { x: 0, y: 'field_length - 36.576' },
          end: { x: 'field_width', y: 'field_length - 36.576' },
        },
        {
          id: '20_yard_line_2',
          type: 'line',
          description: '20 yard line',
          start: { x: 0, y: 'field_length - 27.432' },
          end: { x: 'field_width', y: 'field_length - 27.432' },
        },
        {
          id: '10_yard_line_2',
          type: 'line',
          description: '10 yard line',
          start: { x: 0, y: 'field_length - 18.288' },
          end: { x: 'field_width', y: 'field_length - 18.288' },
        },
      ],
      fixedElements: ['end_zone_top', 'end_zone_bottom', 'goal_line_top', 'goal_line_bottom'],
      specifications: {
        endZoneDepth: 9.144,
        yardLength: 0.9144,
        fieldWidth: 48.8,
        hashMarkSpacing: 5.64,
      },
    },
  },

  // ============================================
  // LACROSSE
  // ============================================
  {
    sport: 'lacrosse',
    name: 'Lacrosse Field',
    description: 'World Lacrosse regulation field',
    minLength: 100,
    maxLength: 110,
    minWidth: 54,
    maxWidth: 60,
    defaultLength: 100,
    defaultWidth: 55,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Field boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_line',
          type: 'line',
          description: 'Center line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'center_circle',
          type: 'circle',
          description: 'Center circle',
          center: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 2.74,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'restraining_line_top',
          type: 'line',
          description: 'Restraining line (top)',
          start: { x: 0, y: 18.29 },
          end: { x: 'field_width', y: 18.29 },
        },
        {
          id: 'restraining_line_bottom',
          type: 'line',
          description: 'Restraining line (bottom)',
          start: { x: 0, y: 'field_length - 18.29' },
          end: { x: 'field_width', y: 'field_length - 18.29' },
        },
        {
          id: 'goal_area_top',
          type: 'circle',
          description: 'Goal crease (top)',
          center: { x: 'field_width / 2', y: 13.72 },
          radius: 2.74,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'goal_area_bottom',
          type: 'circle',
          description: 'Goal crease (bottom)',
          center: { x: 'field_width / 2', y: 'field_length - 13.72' },
          radius: 2.74,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'goal_line_top',
          type: 'line',
          description: 'Goal line (top)',
          start: { x: 0, y: 13.72 },
          end: { x: 'field_width', y: 13.72 },
        },
        {
          id: 'goal_line_bottom',
          type: 'line',
          description: 'Goal line (bottom)',
          start: { x: 0, y: 'field_length - 13.72' },
          end: { x: 'field_width', y: 'field_length - 13.72' },
        },
      ],
      fixedElements: ['center_circle', 'restraining_line_top', 'restraining_line_bottom', 'goal_area_top', 'goal_area_bottom', 'goal_line_top', 'goal_line_bottom'],
      specifications: {
        goalLineDistance: 13.72,
        restrainingLineDistance: 18.29,
        creaseRadius: 2.74,
        centerCircleRadius: 2.74,
        goalWidth: 1.83,
      },
    },
  },

  // ============================================
  // FUTSAL / 5-A-SIDE
  // ============================================
  {
    sport: 'futsal',
    name: 'Futsal Court',
    description: 'FIFA Futsal regulation court',
    minLength: 38,
    maxLength: 42,
    minWidth: 20,
    maxWidth: 25,
    defaultLength: 40,
    defaultWidth: 20,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Court boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_line',
          type: 'line',
          description: 'Halfway line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'center_circle',
          type: 'circle',
          description: 'Center circle',
          center: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 3,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'center_mark',
          type: 'point',
          description: 'Center spot',
          position: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 0.1,
        },
        {
          id: 'penalty_area_top',
          type: 'arc',
          description: 'Penalty area (top)',
          center: { x: 'field_width / 2', y: 0 },
          radius: 6,
          startAngle: 0,
          endAngle: 180,
        },
        {
          id: 'penalty_area_bottom',
          type: 'arc',
          description: 'Penalty area (bottom)',
          center: { x: 'field_width / 2', y: 'field_length' },
          radius: 6,
          startAngle: 180,
          endAngle: 360,
        },
        {
          id: 'penalty_mark_top',
          type: 'point',
          description: 'Penalty spot (top)',
          position: { x: 'field_width / 2', y: 6 },
          radius: 0.1,
        },
        {
          id: 'penalty_mark_bottom',
          type: 'point',
          description: 'Penalty spot (bottom)',
          position: { x: 'field_width / 2', y: 'field_length - 6' },
          radius: 0.1,
        },
        {
          id: 'second_penalty_mark_top',
          type: 'point',
          description: 'Second penalty spot (top)',
          position: { x: 'field_width / 2', y: 10 },
          radius: 0.1,
        },
        {
          id: 'second_penalty_mark_bottom',
          type: 'point',
          description: 'Second penalty spot (bottom)',
          position: { x: 'field_width / 2', y: 'field_length - 10' },
          radius: 0.1,
        },
        {
          id: 'corner_arc_tl',
          type: 'arc',
          description: 'Corner arc (top-left)',
          center: { x: 0, y: 0 },
          radius: 0.25,
          quadrant: 'bottom-right',
        },
        {
          id: 'corner_arc_tr',
          type: 'arc',
          description: 'Corner arc (top-right)',
          center: { x: 'field_width', y: 0 },
          radius: 0.25,
          quadrant: 'bottom-left',
        },
        {
          id: 'corner_arc_bl',
          type: 'arc',
          description: 'Corner arc (bottom-left)',
          center: { x: 0, y: 'field_length' },
          radius: 0.25,
          quadrant: 'top-right',
        },
        {
          id: 'corner_arc_br',
          type: 'arc',
          description: 'Corner arc (bottom-right)',
          center: { x: 'field_width', y: 'field_length' },
          radius: 0.25,
          quadrant: 'top-left',
        },
      ],
      fixedElements: ['center_circle', 'penalty_area_top', 'penalty_area_bottom', 'penalty_mark_top', 'penalty_mark_bottom', 'second_penalty_mark_top', 'second_penalty_mark_bottom', 'corner_arc_tl', 'corner_arc_tr', 'corner_arc_bl', 'corner_arc_br'],
      specifications: {
        centerCircleRadius: 3,
        penaltyAreaRadius: 6,
        penaltyMarkDistance: 6,
        secondPenaltyMarkDistance: 10,
        cornerArcRadius: 0.25,
        goalWidth: 3,
      },
    },
  },

  // ============================================
  // SOCCER 7v7 (YOUTH) - US Youth Soccer Standards
  // ============================================
  {
    sport: 'soccer',
    name: '7v7 Youth Field',
    description: 'Youth soccer field for 7-a-side matches (U9-U10) per US Youth Soccer',
    minLength: 50,
    maxLength: 59,
    minWidth: 32,
    maxWidth: 41,
    defaultLength: 50,
    defaultWidth: 34,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Outer field boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_line',
          type: 'line',
          description: 'Halfway line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'center_circle',
          type: 'circle',
          description: 'Center circle (8 yards radius)',
          center: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 7.3,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'center_mark',
          type: 'point',
          description: 'Center spot',
          position: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 0.15,
        },
        {
          id: 'goal_area_top',
          type: 'rectangle',
          description: 'Goal area (top) - 8 yards wide x 4 yards deep',
          position: { x: '(field_width - 7.3) / 2', y: 0 },
          size: { width: 7.3, height: 3.7 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'goal_area_bottom',
          type: 'rectangle',
          description: 'Goal area (bottom) - 8 yards wide x 4 yards deep',
          position: { x: '(field_width - 7.3) / 2', y: 'field_length - 3.7' },
          size: { width: 7.3, height: 3.7 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'penalty_area_top',
          type: 'rectangle',
          description: 'Penalty area (top) - 24 yards wide x 12 yards deep',
          position: { x: '(field_width - 22) / 2', y: 0 },
          size: { width: 22, height: 11 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'penalty_area_bottom',
          type: 'rectangle',
          description: 'Penalty area (bottom) - 24 yards wide x 12 yards deep',
          position: { x: '(field_width - 22) / 2', y: 'field_length - 11' },
          size: { width: 22, height: 11 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'penalty_mark_top',
          type: 'point',
          description: 'Penalty spot (top) - 10 yards from goal',
          position: { x: 'field_width / 2', y: 9.1 },
          radius: 0.15,
        },
        {
          id: 'penalty_mark_bottom',
          type: 'point',
          description: 'Penalty spot (bottom) - 10 yards from goal',
          position: { x: 'field_width / 2', y: 'field_length - 9.1' },
          radius: 0.15,
        },
        {
          id: 'build_out_line_top',
          type: 'line',
          description: 'Build-out line (top) - midway between penalty area and halfway line',
          start: { x: 0, y: '(11 + field_length / 2) / 2' },
          end: { x: 'field_width', y: '(11 + field_length / 2) / 2' },
        },
        {
          id: 'build_out_line_bottom',
          type: 'line',
          description: 'Build-out line (bottom) - midway between penalty area and halfway line',
          start: { x: 0, y: 'field_length - ((11 + field_length / 2) / 2)' },
          end: { x: 'field_width', y: 'field_length - ((11 + field_length / 2) / 2)' },
        },
        {
          id: 'corner_arc_tl',
          type: 'arc',
          description: 'Corner arc (top-left)',
          center: { x: 0, y: 0 },
          radius: 0.91,
          quadrant: 'bottom-right',
        },
        {
          id: 'corner_arc_tr',
          type: 'arc',
          description: 'Corner arc (top-right)',
          center: { x: 'field_width', y: 0 },
          radius: 0.91,
          quadrant: 'bottom-left',
        },
        {
          id: 'corner_arc_bl',
          type: 'arc',
          description: 'Corner arc (bottom-left)',
          center: { x: 0, y: 'field_length' },
          radius: 0.91,
          quadrant: 'top-right',
        },
        {
          id: 'corner_arc_br',
          type: 'arc',
          description: 'Corner arc (bottom-right)',
          center: { x: 'field_width', y: 'field_length' },
          radius: 0.91,
          quadrant: 'top-left',
        },
      ],
      fixedElements: ['center_circle', 'goal_area_top', 'goal_area_bottom', 'penalty_area_top', 'penalty_area_bottom', 'penalty_mark_top', 'penalty_mark_bottom', 'corner_arc_tl', 'corner_arc_tr', 'corner_arc_bl', 'corner_arc_br'],
      specifications: {
        centerCircleRadius: 7.3,
        goalAreaWidth: 7.3,
        goalAreaDepth: 3.7,
        penaltyAreaWidth: 22,
        penaltyAreaDepth: 11,
        penaltyMarkDistance: 9.1,
        cornerArcRadius: 0.91,
        goalWidth: 3.66,
        goalHeight: 1.98,
      },
    },
  },

  // ============================================
  // SOCCER 9v9 (YOUTH) - US Youth Soccer Standards
  // ============================================
  {
    sport: 'soccer',
    name: '9v9 Youth Field',
    description: 'Youth soccer field for 9-a-side matches (U11-U12) per US Youth Soccer',
    minLength: 64,
    maxLength: 73,
    minWidth: 41,
    maxWidth: 50,
    defaultLength: 64,
    defaultWidth: 46,
    interiorElements: {
      elements: [
        {
          id: 'outer_boundary',
          type: 'rectangle',
          description: 'Outer field boundary',
          position: { x: 0, y: 0 },
          size: { width: 'field_width', height: 'field_length' },
        },
        {
          id: 'center_line',
          type: 'line',
          description: 'Halfway line',
          start: { x: 0, y: 'field_length / 2' },
          end: { x: 'field_width', y: 'field_length / 2' },
        },
        {
          id: 'center_circle',
          type: 'circle',
          description: 'Center circle (8 yards radius)',
          center: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 7.3,
          radius_unit: 'meters_fixed',
        },
        {
          id: 'center_mark',
          type: 'point',
          description: 'Center spot',
          position: { x: 'field_width / 2', y: 'field_length / 2' },
          radius: 0.15,
        },
        {
          id: 'goal_area_top',
          type: 'rectangle',
          description: 'Goal area (top) - 16 yards wide x 5 yards deep',
          position: { x: '(field_width - 14.6) / 2', y: 0 },
          size: { width: 14.6, height: 4.6 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'goal_area_bottom',
          type: 'rectangle',
          description: 'Goal area (bottom) - 16 yards wide x 5 yards deep',
          position: { x: '(field_width - 14.6) / 2', y: 'field_length - 4.6' },
          size: { width: 14.6, height: 4.6 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'penalty_area_top',
          type: 'rectangle',
          description: 'Penalty area (top) - 36 yards wide x 14 yards deep',
          position: { x: '(field_width - 33) / 2', y: 0 },
          size: { width: 33, height: 12.8 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'penalty_area_bottom',
          type: 'rectangle',
          description: 'Penalty area (bottom) - 36 yards wide x 14 yards deep',
          position: { x: '(field_width - 33) / 2', y: 'field_length - 12.8' },
          size: { width: 33, height: 12.8 },
          size_unit: 'meters_fixed',
        },
        {
          id: 'penalty_mark_top',
          type: 'point',
          description: 'Penalty spot (top) - 10 yards from goal',
          position: { x: 'field_width / 2', y: 9.1 },
          radius: 0.15,
        },
        {
          id: 'penalty_mark_bottom',
          type: 'point',
          description: 'Penalty spot (bottom) - 10 yards from goal',
          position: { x: 'field_width / 2', y: 'field_length - 9.1' },
          radius: 0.15,
        },
        {
          id: 'penalty_arc_top',
          type: 'arc',
          description: 'Penalty arc (top) - 8 yards radius',
          center: { x: 'field_width / 2', y: 9.1 },
          radius: 7.3,
          startAngle: 37,
          endAngle: 143,
        },
        {
          id: 'penalty_arc_bottom',
          type: 'arc',
          description: 'Penalty arc (bottom) - 8 yards radius',
          center: { x: 'field_width / 2', y: 'field_length - 9.1' },
          radius: 7.3,
          startAngle: 217,
          endAngle: 323,
        },
        {
          id: 'corner_arc_tl',
          type: 'arc',
          description: 'Corner arc (top-left)',
          center: { x: 0, y: 0 },
          radius: 0.91,
          quadrant: 'bottom-right',
        },
        {
          id: 'corner_arc_tr',
          type: 'arc',
          description: 'Corner arc (top-right)',
          center: { x: 'field_width', y: 0 },
          radius: 0.91,
          quadrant: 'bottom-left',
        },
        {
          id: 'corner_arc_bl',
          type: 'arc',
          description: 'Corner arc (bottom-left)',
          center: { x: 0, y: 'field_length' },
          radius: 0.91,
          quadrant: 'top-right',
        },
        {
          id: 'corner_arc_br',
          type: 'arc',
          description: 'Corner arc (bottom-right)',
          center: { x: 'field_width', y: 'field_length' },
          radius: 0.91,
          quadrant: 'top-left',
        },
      ],
      fixedElements: ['center_circle', 'goal_area_top', 'goal_area_bottom', 'penalty_area_top', 'penalty_area_bottom', 'penalty_mark_top', 'penalty_mark_bottom', 'penalty_arc_top', 'penalty_arc_bottom', 'corner_arc_tl', 'corner_arc_tr', 'corner_arc_bl', 'corner_arc_br'],
      specifications: {
        centerCircleRadius: 7.3,
        goalAreaWidth: 14.6,
        goalAreaDepth: 4.6,
        penaltyAreaWidth: 33,
        penaltyAreaDepth: 12.8,
        penaltyMarkDistance: 9.1,
        penaltyArcRadius: 7.3,
        cornerArcRadius: 0.91,
        goalWidth: 5.5,
        goalHeight: 2.0,
      },
    },
  },
]

async function main() {
  console.log('Starting database seed for all sports...')

  for (const template of templates) {
    const existing = await prisma.fieldTemplate.findFirst({
      where: {
        sport: template.sport,
        name: template.name,
      },
    })

    if (existing) {
      console.log(`Updating: ${template.name}`)
      await prisma.fieldTemplate.update({
        where: { id: existing.id },
        data: template,
      })
    } else {
      console.log(`Creating: ${template.name}`)
      await prisma.fieldTemplate.create({
        data: template,
      })
    }
  }

  console.log(`\nDatabase seed completed! Created/updated ${templates.length} templates.`)
}

main()
  .catch((e) => {
    console.error('Seed error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
